### ISSUE TITLE
Negative Result

### ISSUE THREAD

**Issue by g33xter** [phishai/phish-ai-api#1]
Hi,

The below result is of your app & I tried it on my phish page. It's saying clean. I'm using @UndeadSec's SocialPhish. It takes advantage of Ngrok.
![screen shot 2018-04-18 at 02 04 37](https://user-images.githubusercontent.com/8503135/38922469-16a8adbe-42ad-11e8-9e31-6cfe22c7c9e9.png)

**Comment by yevgenypats** [comment]
Hey, Thanks for the report. We still have false-positives false negatives. We add this sample to our training set and we will push the fix later today.

**Comment by yevgenypats** [comment]
Should be fixed by now, The site is down so I cannot easily check this. But if you can get another one up and running and check it quickly I'll appreciate this.

**Comment by g33xter** [comment]
Hey, Thanks for the resolve. Attached the result. 

![screen shot 2018-04-19 at 03 47 48](https://user-images.githubusercontent.com/8503135/38987429-900a4348-4384-11e8-9ea3-43c8460dd101.png)

**Comment by g33xter** [comment]
But, If I use different brand/company then it's saying "clean". Check for Social-Fish project for other phishing web-pages.
![screen shot 2018-04-19 at 03 51 37](https://user-images.githubusercontent.com/8503135/38987551-0f405724-4385-11e8-86b1-7167d063e6c3.png)

**Comment by yevgenypats** [comment]
Hey, we constantly run through a lot of phishing feed and add them to our learning engine.
As I said the engine is still in Beta and False positives/negatives can occur.
Anyway we're going to add a special feature with a dispute button so you can click on it instead of filing an Issue for every false positive/negative it will go to our security analyst and if the dispute is correct then we will put it through our learning engine.

Once we add this feature I'll mark it as resolved.

social-fish is noted and we will add those pages to our learning engine.

**Comment by g33xter** [comment]
That'd be great. Thanks.

**Comment by yevgenypats** [comment]
Hey @g33xter, We added the dispute feature. I'll be happy to get feedback from you and I'll close this issue after that.

**Comment by g33xter** [comment]
Hey, looks good. I have raised a dispute on latest phish page there. I don't know whether you received or not.

**Comment by yevgenypats** [comment]
Great. Yes, I got it. Closing the issue. Thx!
